### ISSUE TITLE
Werkzeug 3.0.x support

### ISSUE THREAD

**Issue by TheZoc** [pallets-eco/flask-openid#70]
Currently, Werkzeug 3.0.x isn't compatible with flask-openid.

```python
File "venv/lib/python3.11/site-packages/flask_openid.py", line 23, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 
```

it's a pretty simple fix from here: https://werkzeug.palletsprojects.com/en/2.3.x/urls/

replace the single `url_quote()` call with `urllib.parse.quote()` on `flask_openid.py`.

I can submit a PR if you prefer me to do so :)

**Comment by alex-ball** [comment]
For anyone affected by this, here is a workaround that can be used while the issue persists.

Before importing `flask_openid`, insert the following lines:

```python
import urllib.parse
import werkzeug.urls
werkzeug.urls.url_quote = urllib.parse.quote
```

**Comment by TheZoc** [comment]
@alex-ball I'd recommend against monkey-patching it like that, as it can introduce other unintended issues.
It's easy to modify the library locally instead of propagating that change everywhere else :)

**Comment by alex-ball** [comment]
@TheZoc I take your point and will edit the comment accordingly, but I'd recommend against modifying the library locally since then any tests you run against your script/application will only be valid in that one local environment, and will not be reproducible across machines/installations. Indeed, attempting to deploy to any environment where the library hasn't been manually modified will fail with the error you reported.

My suggestion was offered in the light of [CVE-2023-46136](https://www.cve.org/CVERecord?id=CVE-2023-46136) affecting Werkzeug <= 3.0.1, which has made all this rather more urgent.

**Comment by TheZoc** [comment]
Added PR #71

**Comment by TheZoc** [comment]
@alex-ball Thanks for the CVE link, wasn't aware of it

**Comment by EminUZUN** [comment]
Hello,
Is there any maintainer?
@davidism  @potiuk @puiterwijk

**Comment by Yuval-Moshe** [comment]
Hi, facing this issue also when upgrading Apache superset to the latest version (4.0.1), can someone please approve the attached PR so we can continue using the library? 
@davidism @potiuk @puiterwijk
Thanks
